default_settings: null
behaviors:
  Player1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 20000
      learning_rate: 0.0001
      beta: 0.001
      epsilon: 0.5
      lambd: 0.99
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 2000
  Player2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 20000
      learning_rate: 0.0001
      beta: 0.001
      epsilon: 0.5
      lambd: 0.99
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 2000
